# Generated by Django 5.1.2 on 2024-10-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0002_billingaddress_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='ordered_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ecom_app.product'),
            preserve_default=False,
        ),
    ]
