# Generated by Django 5.1.2 on 2024-10-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0003_alter_ordermodel_ordered_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ordered_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom_app.billingaddress', verbose_name='Billing_adress'),
        ),
    ]
