# Generated by Django 5.1.2 on 2024-10-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0004_ordermodel_ordered_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='delivered_at',
        ),
    ]
