# Generated by Django 5.1.2 on 2024-10-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0006_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
