# Generated by Django 5.1.2 on 2024-10-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0008_alter_cart_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_order',
            old_name='prodcut',
            new_name='product',
        ),
    ]
