# Generated by Django 5.1.2 on 2024-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0010_cart_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
