# Generated by Django 5.1.2 on 2024-10-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0011_alter_ordermodel_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='total_price',
        ),
    ]
