# Generated by Django 5.1.2 on 2024-10-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0013_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_cashon',
            field=models.BooleanField(default=True),
        ),
    ]
