# Generated by Django 5.1.2 on 2024-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0017_payment_details_order_payment_details_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
