# Generated by Django 5.1.2 on 2024-10-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0019_remove_ordermodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
