# Generated by Django 5.1.2 on 2024-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0020_payment_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
